# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
  CNAME:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gh-pages'
    steps:
       - name: write_CNAME
         run: echo '0xdeada1u5.csd.uoc.gr' > 'CNAME'
